# Generated by Django 5.2.3 on 2025-06-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=50)),
                ('quantity_prepared', models.IntegerField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('price', models.FloatField()),
            ],
        ),
    ]
