# Generated by Django 5.2.3 on 2025-06-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='sales_closed',
            field=models.BooleanField(default=False),
        ),
    ]
