# Generated by Django 5.2.3 on 2025-06-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0002_fooditem_sales_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity_wasted',
            field=models.IntegerField(default=0),
        ),
    ]
