# Generated by Django 5.2.3 on 2025-06-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_manager', '0003_auto_20250630_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity_wasted',
        ),
    ]
